-- Tabelas principais
CREATE TABLE public.produto (
    id_produto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_produto TEXT NOT NULL,
    descricao TEXT,
    preco DECIMAL(10, 2) NOT NULL,
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL, -- id do usuário que criou (referência para auth.users.id)
  categoria TEXT DEFAULT 'bebidas', -- categoria do produto (bebidas, cafe, doces, chas, salgados)
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.perfil (
    id_user UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    nome TEXT,
    cep TEXT,
    cidade TEXT,
    estado TEXT,
    rua TEXT,
    bairro TEXT,
    complemento TEXT,
    sexo TEXT,
    telefone TEXT,
    data_nascimento DATE,
    foto TEXT -- URL para a imagem de perfil
);

CREATE TABLE public.escola (
    id_escola BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_escola TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.lanchonete (
    id_lanchonete BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_escola BIGINT NOT NULL REFERENCES public.escola(id_escola) ON DELETE CASCADE,
    nome_lanchonete TEXT NOT NULL,
    id_senac TEXT,
    id_sesc TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.pedido (
    id_pedido BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_lanchonete BIGINT NOT NULL REFERENCES public.lanchonete(id_lanchonete) ON DELETE RESTRICT,
    -- Vincula o pedido diretamente ao usuário do Supabase Auth
    id_user_cliente UUID REFERENCES auth.users(id) ON DELETE SET NULL, -- removido NOT NULL para permitir ON DELETE SET NULL
    status_pedido TEXT DEFAULT 'Pendente',
    valor_total DECIMAL(10, 2) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.itens_pedido (
    id_pedido BIGINT NOT NULL REFERENCES public.pedido(id_pedido) ON DELETE CASCADE,
    id_produto BIGINT NOT NULL REFERENCES public.produto(id_produto) ON DELETE RESTRICT,
    quantidade INT NOT NULL CHECK (quantidade > 0),
    preco_unitario DECIMAL(10, 2) NOT NULL,
    PRIMARY KEY (id_pedido, id_produto)
);

-- Executar este script no SQL Editor do Supabase

ALTER TABLE IF EXISTS public.produto
  ADD COLUMN IF NOT EXISTS created_by uuid;

-- 1.b) Garante que a coluna categoria exista (texto) e um default
ALTER TABLE IF EXISTS public.produto
  ADD COLUMN IF NOT EXISTS categoria text;

-- define default se a coluna existir
ALTER TABLE IF EXISTS public.produto
  ALTER COLUMN categoria SET DEFAULT 'bebidas';

-- adiciona constraint CHECK para limitar os valores permitidos (idempotente)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'produto_categoria_check'
  ) THEN
    ALTER TABLE public.produto
      ADD CONSTRAINT produto_categoria_check CHECK (categoria IN ('bebidas','cafe','doces','chas','salgados'));
  END IF;
END
$$;
-- 2) Habilita Row Level Security na tabela produto
ALTER TABLE IF EXISTS public.produto ENABLE ROW LEVEL SECURITY;

-- 3) Permitir SELECT para usuários autenticados
DROP POLICY IF EXISTS "Produtos - select para autenticados" ON public.produto;
CREATE POLICY "Produtos - select para autenticados"
  ON public.produto
  FOR SELECT
  USING (auth.role() = 'authenticated');

-- 4) Permitir INSERT somente quando created_by = auth.uid()
DROP POLICY IF EXISTS "Produtos - insert own" ON public.produto;
CREATE POLICY "Produtos - insert own"
  ON public.produto
  FOR INSERT
  WITH CHECK (created_by = auth.uid());

-- 5) Permitir UPDATE somente para o criador (created_by = auth.uid())
DROP POLICY IF EXISTS "Produtos - update own" ON public.produto;
CREATE POLICY "Produtos - update own"
  ON public.produto
  FOR UPDATE
  USING (created_by = auth.uid())
  WITH CHECK (created_by = auth.uid());

-- 6) Permitir DELETE somente para o criador (created_by = auth.uid())
DROP POLICY IF EXISTS "Produtos - delete own" ON public.produto;
CREATE POLICY "Produtos - delete own"
  ON public.produto
  FOR DELETE
  USING (created_by = auth.uid());

-- Substitui/Cria a policy solicitada: permitir INSERT apenas para usuários autenticados
DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON public.produto;
CREATE POLICY "Enable insert for authenticated users only"
  ON public.produto
  FOR INSERT
  USING (auth.role() = 'authenticated')
  WITH CHECK (true);

--------------------------------------------------------------------------------
-- ALTERNATIVA: permitir INSERTs por qualquer usuário autenticado (sem created_by)
-- Se preferir essa abordagem, comente/remova a policy "Produtos - insert own"
-- e descomente as linhas abaixo:
--------------------------------------------------------------------------------
-- DROP POLICY IF EXISTS "Produtos - insert own" ON public.produto;
-- CREATE POLICY "Produtos - insert autenticados"
--   ON public.produto
--   FOR INSERT
--   WITH CHECK (auth.role() = 'authenticated');

-- Observações rápidas:
-- - Após executar, verifique que seus clientes enviam created_by = auth.user().id (ou supabase.auth.getUser()) ao inserir,
--   ou use a policy alternativa comentada se não quiser enviar created_by.
-- - Não exponha a service_role key no cliente; use backend seguro para operações administrativas.
